deviation_range and consensus_num fields added
ergoplatform/explorer-frontend pull request #95
Opened 2020-12-16 19:32 UTC by YBLex

![image](https://user-images.githubusercontent.com/43601702/102397156-8faa4880-3fee-11eb-8b52-3d6348f8a3a5.png)

2020-12-16 19:32 UTC, YBLex commented
@deadit

2020-12-16 19:34 UTC, deadit requested changes

2020-12-16 19:34 UTC, deadit commented on src/pages/oracle-pool-state/oracle-pool-state.component.tsx
> +  console.log('>> data', data);
это зачем?

2020-12-16 19:34 UTC, deadit commented on src/pages/oracle-pool-state/oracle-pool-state.component.tsx
> +  console.log('>> technicalData', technicalData);
и это зачем?

2020-12-17 07:39 UTC, YBLex commented
@deadit

2020-12-27 20:11 UTC, merged